# Generated by Django 6.0.4 on 2026-04-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading_system', '0003_faculty_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
